name: run and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run TestProject1 tests
      run: dotnet test TestProject1/TestProject1.csproj --no-build --verbosity minimal
    - name: Run TestProject2 tests
      run: dotnet test TestProject2/TestProject2.csproj --no-build --verbosity normal
    - name: Run TestProject3 tests
      run: dotnet test TestProject3/TestProject3.csproj --no-build --verbosity quiet
